Refactor type names, move components out of util
nfx/slrp pull request #129
Opened 2023-06-28 17:29 UTC by SriramKeerthi

2023-06-28 17:56 UTC, nfx requested changes

2023-06-28 17:56 UTC, nfx commented on ui/src/Dashboard.tsx
> +type CardEntry = {
Please use the same type names as in Go

2023-07-12 09:02 UTC, SriramKeerthi commented
@nfx ready to review again

2023-07-20 10:12 UTC, nfx approved these changes

2023-07-20 10:12 UTC, merged